import {defineType, defineField} from 'sanity'

export const article = defineType({
  name: 'article',
  title: 'Article',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'relations', title: 'Relationships'},
    {name: 'editorial', title: 'Editorial Workflow'},
    {name: 'ai', title: 'AI & Personalization'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'localizedString',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title.en', maxLength: 200},
    }),
    defineField({name: 'excerpt', title: 'Excerpt', type: 'localizedString', group: 'content'}),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      group: 'content',
      options: {hotspot: true},
      fields: [
        {name: 'alt', type: 'string', title: 'Alt Text'},
        {name: 'caption', type: 'string', title: 'Caption'},
        {name: 'credit', type: 'string', title: 'Credit'},
      ],
    }),
    defineField({name: 'body', title: 'Body', type: 'localizedBlockContent', group: 'content'}),
    defineField({
      name: 'articleType',
      title: 'Article Type',
      type: 'string',
      group: 'content',
      options: {
        list: [
          {title: 'News', value: 'news'},
          {title: 'Feature', value: 'feature'},
          {title: 'Analysis', value: 'analysis'},
          {title: 'Opinion', value: 'opinion'},
          {title: 'Interview', value: 'interview'},
          {title: 'Live Blog', value: 'liveblog'},
        ],
      },
    }),
    defineField({
      name: 'sport',
      title: 'Sport',
      type: 'reference',
      to: [{type: 'sport'}],
      group: 'relations',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'relatedPlayers',
      title: 'Related Players',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'player'}]}],
      group: 'relations',
    }),
    defineField({
      name: 'relatedTeams',
      title: 'Related Teams',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'team'}]}],
      group: 'relations',
    }),
    defineField({
      name: 'relatedTournaments',
      title: 'Related Tournaments',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'tournament'}]}],
      group: 'relations',
    }),
    defineField({
      name: 'relatedProducts',
      title: 'Related Products',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'product'}]}],
      group: 'relations',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{type: 'author'}],
      group: 'editorial',
    }),
    defineField({name: 'publishedAt', title: 'Published At', type: 'datetime', group: 'editorial'}),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'editorial',
      options: {list: ['draft', 'in-review', 'published', 'archived'], layout: 'radio'},
      initialValue: 'draft',
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured Article',
      type: 'boolean',
      group: 'editorial',
      initialValue: false,
    }),
    defineField({name: 'contentContext', type: 'contentContext', group: 'ai'}),
    defineField({name: 'seo', type: 'seo', group: 'seo'}),
  ],
  orderings: [
    {title: 'Published (Newest)', name: 'publishedDesc', by: [{field: 'publishedAt', direction: 'desc'}]},
  ],
  preview: {
    select: {title: 'title.en', type: 'articleType', date: 'publishedAt', media: 'heroImage'},
    prepare: ({title, type, date, media}) => ({
      title,
      subtitle: `${type || 'article'} — ${date ? new Date(date as string).toLocaleDateString() : 'unpublished'}`,
      media,
    }),
  },
})
